cd TestExecutive/bin/Debug
start TestExecutive.exe
cd ../../../
cd GUI/bin/Debug
start GUI.exe
cd ../../../
cd RepoMock/bin/Debug
start RepoMock.exe
cd ../../../
cd BuildServer/bin/Debug
start BuildServer.exe